moov-io/customers

cmd/server/customers.go, cmd/server/customers_test.go
Not every CustomerStatus can be converted into another, so we need to block bad transistions.
Issue: https://github.com/moov-io/customers/issues/5
=> cmd/server: whitelist only certain CustomerStatus transistions

cmd/server/customers.go
Instead of attaching it in respondWithCustomer we should always read
the metadata for a Customer on getCustomer repository calls.
=> cmd/server: include Customer metadata in getCustomer repository method

README.md, cmd/server/approval.go
After upgrading to v0.11.0 OFAC's search and ranking has been improved
so we need to be less tolerant of low quality matches.
=> ofac: bump minimum threshold to 99% matches

cmd/server/approval.go, cmd/server/approval_test.go, cmd/server/customers.go, cmd/server/customers_test.go, cmd/server/main.go
Creating a customer might involve adding data in several steps. This is the case with paygate where initially there isn't enough information to always create a Customer. In the case of a Receiver there's no SSN to attach (and one isn't needed to push money at a Receiver).
Let's loosen the requirements for a Customer and verify the data when status transitions happen. 
Issue: https://github.com/moov-io/paygate/issues/98
=> cmd/server: allow email, phones, and addresses to be optional on a Customer

.travis.yml, cmd/server/watchman.go, cmd/server/watchman_test.go
When doing OFAC searches for a Customer these will either be an individual or entiy (corporation) and never something like a vessel. We need to add those filters to searches and find which matched higher.
=> cmd/server: lookup individual and entiy SDNs from Watchman

cmd/server/accounts/repository.go, cmd/server/accounts/router_test.go
Rather than null, which is harder for a UI to deal with.
=> accounts: return an empty array if no accounts are found

client/README.md, client/api/openapi.yaml, client/docs/Account.md, client/docs/InstitutionAddress.md, client/docs/InstitutionDetails.md, client/model_institution_address.go, client/model_institution_details.go, cmd/server/accounts/router.go, cmd/server/fed/cache.go, cmd/server/fed/cache_test.go, cmd/server/fed/client.go, cmd/server/fed/client_test.go, cmd/server/fed/fed.go, cmd/server/fed/mock_client.go, cmd/server/main.go, go.mod, go.sum, openapi.yaml
This was requested by @joshsadler for the UI. It'll include FI information related to each `Account`. 
Example:
```
$ curl -s localhost:8087/customers/52840ffb2becc6633778e9689e5c9bb50f7ce151/accounts | jq . 
```
```json
[
{
"accountID": "375e4036a22b928b4bba4a63eb3ed5c2471be84d",
"maskedAccountNumber": "******1000",
"routingNumber": "323274270",
"status": "validated",
"type": "Checking",
"institution": {
"name": "OREGON STATE CREDIT UNION",
"routingNumber": "323274270",
"phoneNumber": "5417144000",
"address": {
"address1": "PO BOX 306",
"city": "CORVALLIS",
"state": "OR",
"zip": "97339"
}
}
}
]
```
=> accounts: return InstitutionDetails next to routing number

cmd/server/customer_search.go, cmd/server/customer_search_test.go
This PR updates the search functionality for Customers to allow searching by Status.
=> Update customer search functionality to allow searching for Customer by Status.

cmd/server/customer_search.go, cmd/server/customer_search_test.go
This PR changes the customer search `order by` clause to use `desc` so we return the newest results and not the oldest.
=> change search from asc to desc to get newest

cmd/server/customer_search.go, cmd/server/customer_search_test.go
In Go JSON marshaling will render 'null' for an unallocated array and '[]' for an allocated array. This is unexpected by some JS apps that will fail to treat null like an empty array.
As a result of our X-Namespace change the first query in searchCustomers can return zero results which will return the unallocated array to the UI.
=> search: always return an allocated array for JSON marshal

cmd/server/customer_search_test.go
This PR refactors a test 'TestGetCustomersWithVerifiedStatus' that was failing intermittently. I changed this test to more deterministically create customers and reliably change the status on one customer.
To ensure the test no longer fails intermittently, I ran `go test ./cmd/server/ -count 100 -run TestGetCustomersWithVerifiedStatus -v ` and the test no longer fails.
=> fix flakey test

api/client.yaml, pkg/client/README.md, pkg/client/api/openapi.yaml, pkg/client/api_customers.go, pkg/client/docs/CustomersApi.md, pkg/customers/approval_test.go, pkg/customers/customer_search_scope_test.go, pkg/customers/customer_search_test.go, pkg/customers/customers.go, pkg/customers/customers_test.go
This endpoint accepts the same payload used in creating a customer and returns the entire customer object after a successful update.
Fixes #175
=> http: Add endpoint to update a Customer

internal/database/mysql.go, internal/database/sqlite.go
Send migrator output to log instead of stdout
=> set logger for database migrator (instead of default stdout)

pkg/documents/disclaimers.go, pkg/documents/documents.go, pkg/documents/documents_test.go
Performs a check against `customers.namespace` when fetching customer documents.
Fixes #190
=> documents: check namespace match on customers when fetching documents

pkg/configuration/router.go, pkg/configuration/router_test.go
This PR fixes a grievous and, in retrospect, obvious error in my previous PR (for #194). When the requested logo image file isn't found in the storage bucket, the endpoint will now respond with 404 not found.
=> return 404 for logo not found

api/admin.yaml, api/client.yaml, cmd/server/main.go, pkg/accounts/mock_repository.go, pkg/accounts/repository.go, pkg/accounts/repository_test.go, pkg/accounts/router.go, pkg/accounts/router_test.go, pkg/accounts/validate_test.go, pkg/client/README.md, pkg/client/api/openapi.yaml, pkg/client/api_customers.go, pkg/client/docs/Account.md, pkg/client/docs/CustomersApi.md, pkg/client/docs/ReportAccountResponse.md, pkg/client/model_report_account_response.go, pkg/customers/address_test.go, pkg/customers/approval.go, pkg/customers/approval_ofac.go, pkg/customers/customer_search.go, pkg/customers/customer_search_scope_test.go, pkg/customers/customer_search_test.go, pkg/customers/customers.go, pkg/customers/customers_test.go, pkg/reports/router.go, pkg/reports/router_test.go
Adds the endpoint /reports/accounts?accountIDs={...} which returns a list of objects that include customer and account information.
Fixes #196
=> http: add endpoint to fetch a detailed list of customer and account info

pkg/customers/customers.go, pkg/customers/customers_test.go
Fixes #239 and a similar bug related to updating a customer's addresses
Calling `PUT /customers/{id}` should delete any customer phones or addresses not in the request body  — or upsert the specified phone or address values.
=> fix: bug in updating a customer's phones and addresses

api/client.yaml, pkg/client/api/openapi.yaml, pkg/client/api_customers.go, pkg/client/docs/CustomersApi.md, pkg/customers/customer_search.go, pkg/customers/customer_search_test.go, pkg/customers/customers.go, pkg/customers/customers_test.go
This PR makes two main changes:
1. Adds the ability to search by customerIDs: `GET /customers?customerIDs=id_1,id_2`
2. Reduces the number of database queries triggered by `GET /customers`
A call to `GET /customers` that matches `n=25` customers would trigger `~100 or n*4` database queries:
`searchCustomers` would call `getCustomer()` `n` times 
- each call to `getCustomer()` would also trigger 3 additional db queries to fetch the customer's addresses, phones, and metadata.
Thus, `n * ( getCustomer() + getAddresses() + getPhones() + getMetadata() ) -> 25 * (1+1+1+1) = 100` 
Fixes #220 #216
=> Enable searching customers by their IDs and optimize # of database queries

pkg/customers/customer_search_test.go
To temporarily work around mysql and sqlite query syntax, we need to set the test database to use mysql when we make `?query=` calls.
=> fix: set failing test to use mysql

pkg/customers/address.go, pkg/customers/address_test.go, pkg/customers/approval_test.go, pkg/customers/customers.go, pkg/customers/customers_test.go
Ensures that a customer cannot have two address with type `primary` through the various endpoints used to create or update a customer's addresses.
Fixes #215
=> validation: ensure that a primary address is not created if one already exists for the customer
