moov-io/customers

client/README.md
client/api/openapi.yaml
client/api_customers.go
client/docs/Address.md
client/docs/CustomersApi.md
client/model_address.go
cmd/server/approval.go
cmd/server/approval_test.go
cmd/server/customers.go
cmd/server/customers_test.go
cmd/server/main.go
cmd/server/sqlite.go
openapi.yaml

This pull request adds "admin" routes for approving an Address and end-user routes for adding a new Address (which can be approved). 
Issue: https://github.com/moov-io/customers/issues/5

Customer address approval and additions

---

README.md
cmd/server/main.go
cmd/server/main_test.go

Fixes: https://github.com/moov-io/customers/issues/29

cmd/server: bind HTTP server with TLS if HTTPS_* variables are defined

---

.travis.yml

Issue: https://github.com/moov-io/infra/issues/58

build: download CI tools rather than install

---

client/README.md
client/api/openapi.yaml
client/api_customers.go
client/docs/CustomersApi.md
cmd/server/disclaimers.go
cmd/server/disclaimers_test.go
openapi.yaml

Issue: https://github.com/moov-io/paygate/issues/98

cmd/server: add disclaimers to OpenAPI spec, render accepted disclaimer

---

client/README.md
client/api/openapi.yaml
client/api_customers.go
client/docs/CustomersApi.md
cmd/server/approval.go
cmd/server/approval_ofac.go
cmd/server/approval_ofac_test.go
cmd/server/main.go
openapi.yaml

Adding an endpoint to search OFAC for a given customer at any given time. 
Issue: https://github.com/moov-io/paygate/issues/326

cmd/server: add endpoint for manual OFAC refresh

---

client/api/openapi.yaml
client/docs/OfacSearch.md
client/model_ofac_search.go
cmd/server/approval_ofac.go
cmd/server/approval_ofac_test.go
cmd/server/customers.go
openapi.yaml

Kinda need to know when the search was performed.. 
Issue: https://github.com/moov-io/customers/issues/50

cmd/server: include CreatedAt timestamp on ofac search results

---

CHANGELOG.md
cmd/server/customers.go
cmd/server/customers_test.go

See: https://dev.mysql.com/doc/refman/8.0/en/replace.html

cmd/server: fix create customer query for mysql

---

CHANGELOG.md
internal/database/mysql.go

- database/mysql: change customers.status to string
- database/mysql: expand encrypted_account_number

database/mysql: fix columns types and size

---

client/api/openapi.yaml
client/api_customers.go
cmd/server/customers.go
cmd/server/customers_test.go
openapi.yaml

This is better than a 'null' customer.

cmd/server: return 404 if customer isn't found

---

cmd/server/accounts/repository_test.go
internal/database/mysql.go
internal/database/sqlite.go

Fixes: https://github.com/moov-io/customers/issues/107

accounts: reject duplicate accounts for a customer

---

cmd/server/fed/client.go
cmd/server/fed/client_test.go
cmd/server/fed/fed.go
cmd/server/main.go
cmd/server/paygate/client.go
cmd/server/paygate/client_test.go
cmd/server/watchman.go
cmd/server/watchman_test.go
internal/util/util.go
internal/util/util_test.go

Fixes: https://github.com/moov-io/customers/issues/111
Fixes: https://github.com/moov-io/customers/issues/112
Fixes: https://github.com/moov-io/customers/issues/113

fed, paygate, watchman: config for debugging API calls

---

Dockerfile

Fixes: https://github.com/moov-io/customers/issues/125

build: mount sqlite path as volume

---

cmd/server/customer_search.go
cmd/server/customer_search_scope_test.go
cmd/server/customer_search_test.go

This PR adds tests to make sure searching for customers by name and email and a combination of both yields the proper results.

Email and name filtering

---

CONTRIBUTING.md

Fixes: https://github.com/moov-io/customers/issues/136

docs: add contributing.md (from template)

---

api/admin.yaml
api/client.yaml
cmd/server/customer_search.go
cmd/server/customer_search_scope_test.go
cmd/server/customer_search_test.go
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md

This PR introduces the ability to search for customers by type. Currently, there are two customer types, INDIVIDUAL and BUSINESS.

Filter customer by type

---

api/client.yaml
cmd/server/accounts/accounts_ofac.go
cmd/server/accounts/accounts_ofac_test.go
cmd/server/accounts/mock_repository.go
cmd/server/accounts/repository.go
cmd/server/accounts/router.go
cmd/server/accounts/router_test.go
cmd/server/main.go
go.mod
internal/database/mysql.go
internal/database/sqlite.go
pkg/client/README.md
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md

This PR supersedes [https://github.com/moov-io/customers/pull/147](https://github.com/moov-io/customers/pull/147). There were many conflicts in the original and I thought it'd be easier to create a new PR.

account ofac search

---

api/client.yaml
cmd/server/accounts/router.go
cmd/server/accounts/router_test.go
pkg/client/README.md
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md

This PR provides a PUT endpoint that allows an Account ofac search to be updated by running the ofac search again.

Account Ofac Refresh

---

api/client.yaml
pkg/client/api/openapi.yaml
pkg/client/docs/CreateCustomer.md
pkg/client/model_create_customer.go

See: https://github.com/moov-io/quick-enroll/issues/12

api,client: mark SSN as optional on CreateCustomer

---

api/client.yaml
cmd/server/customers.go
cmd/server/customers_test.go
pkg/client/api/openapi.yaml
pkg/client/docs/CreateCustomer.md
pkg/client/docs/Customer.md
pkg/client/model_create_customer.go
pkg/client/model_customer.go
pkg/model/yyyymmdd.go
pkg/model/yyyymmdd_test.go

customers: accept yyyy-mm-dd formatted birthDates

---

README.md
api/client.yaml
cmd/server/approval_test.go
cmd/server/customer_search.go
cmd/server/customer_search_scope_test.go
cmd/server/customer_search_test.go
cmd/server/customers.go
cmd/server/customers_test.go
cmd/server/disclaimers_test.go
cmd/server/documents.go
cmd/server/route/namespace.go
cmd/server/route/namespace_test.go
internal/database/mysql.go
internal/database/sqlite.go
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md
version.go

Fixes: https://github.com/moov-io/customers/issues/146

all: record x-namespace for customers

---

cmd/server/accounts/validator/mx/strategy_test.go

remove all users from dev account after MX test

---

api/client.yaml
cmd/server/customers.go
cmd/server/customers_test.go
pkg/client/README.md
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md

Add http endpoint to delete a customer by its ID
Fixes #174

http: add endpoint to delete a Customer

---

cmd/server/customers.go
internal/database/sqlite.go

The column is called percentage_match, not "match".
Fixes: https://github.com/moov-io/customers/issues/172

customers: fix ofac search query

---

api/client.yaml
cmd/server/accounts/router.go
cmd/server/accounts/router_test.go
pkg/client/README.md
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md

Add http endpoint to get an account by `customerID` and `accountID`
Fixes #170

http: add endpoint to get an Account

---

pkg/customers/customers.go
pkg/customers/customers_test.go

This fixes customers  (#181 was merged with failed ubuntu_build).

fix repo name and router method

---

api/client.yaml
internal/database/mysql.go
internal/database/sqlite.go
pkg/client/README.md
pkg/client/api/openapi.yaml
pkg/client/api_customers.go
pkg/client/docs/CustomersApi.md
pkg/customers/documents.go
pkg/customers/documents_test.go

Added an endpoint to soft delete a customer's document.
Fixes #176

http: endpoint to delete a customer's document

---

pkg/customers/customers.go

fix: creating a customer without a birthday should not result in zero timestamp in response body

---

cmd/server/main.go
cmd/server/main_test.go
docs/CONFIGURATION.md
pkg/documents/documents.go
pkg/documents/documents_test.go
pkg/documents/storage/bucket.go
pkg/documents/storage/bucket_test.go
pkg/documents/storage/test_bucket.go

Fixes: https://github.com/moov-io/customers/issues/129
Fixes: https://github.com/moov-io/customers/issues/198
Issue: https://github.com/moovfinancial/production/issues/42

documents: fixup document storage and retrieval

---

api/admin.yaml
api/client.yaml
pkg/client/api_configuration.go

Issue: https://github.com/moovfinancial/api-docs/issues/162

api,client: update shared Error model

---

.openapi-generator/admin-generator-config.yml
.openapi-generator/client-generator-config.yml
api/client.yaml
pkg/accounts/micro_deposits.go
pkg/accounts/repository.go
pkg/accounts/repository_test.go
pkg/accounts/router.go
pkg/accounts/router_test.go
pkg/accounts/validate.go
pkg/accounts/validate_test.go
pkg/client/api/openapi.yaml
pkg/client/model_account_status.go
pkg/client/model_account_type.go
pkg/client/model_customer_status.go
pkg/client/model_customer_type.go
pkg/customers/approval_ofac.go
pkg/customers/customer_search_test.go
pkg/customers/customers.go
pkg/customers/customers_test.go

Added enum prefixes and 'frozen' to customer account status enums

---

pkg/accounts/mock_repository.go
pkg/accounts/repository.go
pkg/accounts/repository_test.go
pkg/accounts/router.go
pkg/accounts/router_test.go

validate that customer belongs to a ceratin org when fetching accounts

---

pkg/customers/customer_search.go
pkg/customers/customers_test.go
pkg/model/yyyymmdd.go

fix: birthdate not being fetched for customer

---

pkg/customers/customer_search.go
pkg/customers/customers.go
pkg/customers/customers_test.go

fix: bug when fetching customer metadata

---

docs/README.md

As we switched to new type of migrations (migrations in files) we need to describe how it works not. This PR describes migrations in Customers application.
You can see how it looks here: https://github.com/moov-io/customers/blob/b149953870420290b87b785cefc0e0180ca5f4bf/docs/README.md#database-migrations
proof reading is required :D

describe migrations

---

cmd/server/main.go
cmd/server/main_test.go
docs/configuration.md

main: add prevent_insecure_startup
